### PR TITLE
Fix dockerfile permission

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/c9c50ad1bceff8aba0ca8b6e053a20e372d8ec09/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/eb563032306778432ef64a3bbb97172295af7e84/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/43b05f42d118b4be007692dd80cac93a4281dd61/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/3cb0581c1586231d85d6adf070cf02c5a1e09f84/checks) has Failed!

**Review by talha0324 — APPROVED** [review]

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit//checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/developer-handbook:v0.0.48`

**Pull request merged**
