### PR TITLE
Kubernetes concepts

### PR DESCRIPTION
**Pull request by rasheedamir**
- thoroughly explain k8s requests and limits
- thoroughly explain k8s storage

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-1`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-2`

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins-delivery.stakater.com/job/developer-handbook/job/PR-39/3/) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-4`

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins-delivery.stakater.com/job/developer-handbook/job/PR-39/5/) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-6`

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins-delivery.stakater.com/job/developer-handbook/job/PR-39/7/) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-8`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-9`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-10`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-11`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-12`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-13`

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 14](https://jenkins-delivery.stakater.com/job/developer-handbook/job/PR-39/14/) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-15`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-16`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/developer-handbook:SNAPSHOT-PR-39-17`

**Review by josedev-union — APPROVED** [review]
/lgtm

**Pull request merged**
