### PR TITLE
migrate images from nexus to ghcr

### PR DESCRIPTION
**Pull request by bnallapeta**

### CODE REVIEW

**Comment by stakater-user** [comment]
@bnallapeta Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/fc311c43f80f4ad0f52e454192caa7d950e61c2b/checks) has Failed!

**Comment by stakater-user** [comment]
@bnallapeta Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/9f815db26536526f32ea6a3bfe3436cb3d768938/checks) has Failed!

**Review by karl-johan-grahn — APPROVED** [review]

**Comment by stakater-user** [comment]
@bnallapeta Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/7e9f4fa9e3a7b99a5c2eff9629ac74a0e5f4f08c/checks) has Failed!

**Comment by stakater-user** [comment]
@bnallapeta Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/70b3edec3d9d23c28504d32d3f27cfd37e98c622/checks) has Failed!

**Comment by stakater-user** [comment]
@bnallapeta Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/47a7f30062381076209186a2d778010d9b0f55de/checks) has Failed!

**Comment by stakater-user** [comment]
@bnallapeta Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/developer-handbook/commit/b03f6dc21bdfd622107ab0fed172a3430413dce8/checks) has Failed!

**Review by karl-johan-grahn — APPROVED** [review]

**Comment by karl-johan-grahn** [comment]
Force merging since this is a workflow change, it runs based on what is on master, not what is on this branch

**Pull request merged**
